version: '3.8'

services:
  db:
    container_name: catalog_bot_db
    image: postgres:16.4
    environment:
      POSTGRES_USER: catalogbot_user
      POSTGRES_PASSWORD: catalogbot_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catalog_bot_network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432" ]
      interval: 10s
      retries: 5

  app:
    container_name: catalog_bot_api
    image: catalog_bot_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - catalog_bot_network

networks:
  catalog_bot_network:
    driver: bridge

volumes:
  postgres_data:
